# Generated by Django 3.1.7 on 2021-03-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_trackers', '0002_food_profile_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfood',
            name='created_on',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
