# Generated by Django 3.1.7 on 2021-04-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_trackers', '0005_auto_20210327_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
