# Generated by Django 3.1.7 on 2021-04-19 04:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food_trackers', '0006_auto_20210418_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
